sudo: false
language: php

# Cache some data across builds for performance.
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_pull_requests: true
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS

branches:
  only:
    - master

matrix:
  include:
    - php: 7.2
      env: WP_Version=nightly
    - php: 7.1
      env: WP_VERSION=latest WP_TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - |
    if [[ "$WP_TRAVISCI" == "grunt" ]] ; then
      composer install
      npm --version
      node --version
      nvm install stable
      npm install -g grunt-cli
      npm install
      npm prune
      npm --version
      node --version
    fi
  - mysql --version
  - phpenv versions
  - php --version

script:
  - |
    if [[ "$WP_TRAVISCI" == "grunt" ]] ; then
      grunt --version
      grunt default
    fi
